<a href="https://colab.research.google.com/github/Khushi232505/Data-Science-and-AI/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***TensorFlow Fundamentals***

Tensorflow is a python library used to build, train and deploy machine learning and deep learning models.

#***Tensor***

Tensor is a multi-dimensional array used to store and process data.

#***Types of Tensors***

1. Scalar(0D) - 5
2. Vector(1D) - [10,20,30]
3. Matrix(2D) - [[1,2] , [3,4]]
4. 3D tensor - images
5. 4D tesnor - Batch of images



#***Tensorflow workflow***

Collect Dataset -> Preprocess Data -> Convert Data into Tensors -> Build Neural Network -> Train Model -> Evaluate Model -> Make Predictions


#***Keras***

Keras is a high-level API of tensorflow used to build and train deep learning models.

#***Keras workflow***

Import keras -> Create Model -> Add layers -> Compile model -> Train model ->
Evaluate Model -> Predict

In [ ]:
from tensorflow import keras
#OR
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

#Create an empty neural network
model = Sequential()

print(model)

#Add layers

model = Sequential()

#Hidden Layer
model.add(Dense(16, activation = "relu", input_shape = (4,)))

#Hidden Layer
model.add(Dense(8, activation = "relu"))

#Output Layer
model.add(Dense(1, activation = "sigmoid"))


model.summary()

<Sequential name=sequential, built=False>


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 225 (900.00 B)

 Trainable params: 225 (900.00 B)

 Non-trainable params: 0 (0.00 B)

#***Relationship between Tensorflow and Keras***

TensorFlow -> Keras API -> Build Neural Networks -> Train Model -> Predict Results

In [ ]:
#Practical Example 1: Creating Tensors
import tensorflow as tf

#Scalar Tensor (0D)
scalar = tf.constant(10)
print("Scalar:", scalar)

#Vector Tensor (1D)
vector = tf.constant([10, 20, 30])
print("Vector:", vector)

# Matrix Tensor (2D)
matrix = tf.constant([
    [1,2],
    [3,4]
])
print("Matrix : ")
print(matrix)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Matrix : 
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#Practical Example 2:Tensors Operations
import tensorflow as tf

a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))


Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction: tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Multiplication: tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division: tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [ ]:
#Practical Example 3: Matrix Multiplication

import tensorflow as tf

A = tf.constant([
    [1,2],
    [3,4]
])

B = tf.constant([
    [5,6],
    [7,8]
])

result = tf.matmul(A,B)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


#***Building a Neural Network***

Building a Neural Network is the process of creating the structure of ANN by adding layers, neurons, and activation functions using TensorFlow and Keras.

#***Steps to Build a Neural Network***

Import Libraries -> Create Sequential Model -> Add Input Layer -> Add Hidden Layer(s) -> Add Output Layer -> Compile Model -> Train Model -> Make Predictions

#***Components of a neural network***

1. Input Layer
2. Output Layer
3. Hidden Layer

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Create Neural Network
model = Sequential()

#Input + Hidden Layer
model.add(Dense(
    units=16,
    activation = "relu",
    input_shape=(2,)
))

#Hidden Layer
model.add(Dense(
    units=8,
    activation = "relu"
))

#Ouput Layer
model.add(Dense(
    units=1,
    activation = "sigmoid"
))

#Display Model Summary
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

#***Model Compilation in TensorFlow and Keras***
Model Compilation is the process of configuring a nural network by specifying the optimizer, loss function, and evaluation metrics before training.

#***Components:***

1. ***Optimizer*** - An optimizer adjusts the weights of the neural network to minimize the loss and improve prediction accuracy
* adam
* SGD
* RMSprop
* Adagrad

2. ***Loss Function*** - The loss function calculates the prediction error of the neural network.
* binary_crossentropy
* categorical_crossentrpy
* mean_squared_error(MSE)

3. ***Metrics*** - Metrics evaluate how well the neural network is performing.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Create Model
model = Sequential()

#Input + Hidden Layer
model.add(Dense(16, activation = "relu", input_shape = (2,)))

#Hidden Layer
model.add(Dense(8, activation = "relu"))

#Output Layer
model.add(Dense(1, activation = "sigmoid"))

#Compile Model
model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ["accuracy"]
)

model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

#***Training and Valdiation in Tensorflow and Keras***

1. ***Training*** - Training is the process of teaching a neural network using training data so that it can make accurate predictions.

2. ***Validation*** - Validation is the process of checking the model's performance on unseen data during training.



#***Biological VS Artificial Neurons in ANN***

#***Biological Neuron***

A biological neuron is the basic functional unit of the human nervous system. It receives signals from other neurons, processes them, and sends signal to the next neuron.


       Dendrites
       /  |   \
      /   |    \
  Input  Signals
          
          |
          
       Cell Body
        (Soma)

          |

        Axon

          |
        
      Output Signal

#***Artificial Neuron***

An Artificial Neuron is the mathematical model of a biological neuron used in Artificial Neural Networks(ANNs). It receives input values, performs
calculations, applies an activation function, and produces an output.

#***Mapping Between Biological and Artificial Neurons.***

#***Biological Neuron Artificial Neuron***

1. Dendrites ---------> Inputs(X)
2. Synapse -----------> Weights(W)
3. Cell Body ---------> Weighted Sum(Σ)
4. Axon -----------> Output(Y)
5. Brain ---------> Neural Network(ANN)

#***Actiavtion Functions***

An activation function determines the output of a neuron by transforming the weighted sum into a meaningful value.

Inputs(X) --> Weighted Sum(Σ) --> Activation Function --> Output

#***Types of Activation Functions***

1. Binary Step -- The binary step function gives only two outputs(0,1).It is mainly used in perception model

2. Sigmoid Function -- It converts any input into a value between 0 and 1.

3. Tanh Function -- The tanh functions output values between -1 and +1.

4. ReLU(Rectified Linear Unit) -- It is used activation function in deep learning

5. Leaky ReLU -- Leaky ReLU is an improved version of ReLU. Instead of returning 0 for negative values, it returns a small negative value.

6. Softmax -- Softmaxx is used for Multi-Class Classification .
It converts outputs into probabilties whose total is 1.

#***Perception Model***

A Perception is the simplest Artificial Neural Network(ANN) and is the building block of deep learning. It was introduced by Frank Rosenblatt in 1958.

It is mainly used for Binary Classification, where the output has only two classes:

1. Yes/No
2. Pass/Fail
3. Spam/Not Spam
4. Survived/Not Survived

In [1]:
import numpy as np

# Inputs
hours = 8
attendance = 90

# Weights
w1 = 0.6
w2 = 0.4

# Bias
bias = -4

# Weighted Sum
z = (hours  * w1) + (attendance * w2) + bias

print("Weighted Sum : ", z)

# Step Activation Function
if z>= 0:
  print("Prediction : Pass")
else:
  print("Prediction : Fail")

Weighted Sum :  36.8
Prediction : Pass


#***Feed Forward Neural Network(FFNN)***

A Feed Forward Neural Network is a neural network where information moves only from the input layer to the output layer without any backward connections.

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Create Feed Forward Neural Netwrok
model = Sequential()

#Input + Hidden Layer
model.add(Dense(16, activation = "relu", input_shape = (7,)))

#Hidden Layer
model.add(Dense(8, activation = "relu"))

#Output Layer
model.add(Dense(1, activation = "sigmoid"))

# Display Model Architecture
model.summary()



/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 273 (1.07 KB)

 Trainable params: 273 (1.07 KB)

 Non-trainable params: 0 (0.00 B)