<a href="https://colab.research.google.com/github/Khushi232505/Data-Science-and-AI/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy Fundamentals***

# **What is NumPy?**

NumPy (Numerical Python) is a powerful python library used for:
1. Numerical computations.
2. Working with arrays and matrices.
3. Mathmatical operations
4. Data Science and Machine learning

# ***Why use NumPy?***

1. faster than data list.
2. less memomry usage.
3. supoorts multi dimension arrays.
4. provide mathmatical and statistical functions.

1. Installing Numpy

In [ ]:
pip install numpy

import NumPy


In [2]:
import numpy as np


2. Creating NumPy Arrays

# ***Arrays***

An array is a data structure used to store multiple values of the same data type in a single variable.

From a list

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# ***Two-Dimensional Array(2D)***

A 2D array is an array that stores data in rows and columns, just like an excel sheet or matrix
*italicized text*

In [4]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


# ***Three-Dimensional Array(3D)***

A 3D array is an array that has three dimensions:

1. Depth(Layers)
2. Rows
3. Columns

In [5]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ***Array Attributes***

NumPy array attributes provide important information about an array, such as its dimensions, size, shape, and data type.


In [6]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

print("Shape: ", arr.shape)
print("Dimensions: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimensions:  2
Size:  6
Data Type:  int64


# ***Special Arrays***


# ***zeros Array np.zeros().***

Creates an array where every element is 0.

In [8]:
import numpy as np

arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
