# ***NumPy Fundamentals***

# **What is NumPy?**

NumPy (Numerical Python) is a powerful python library used for:
1. Numerical computations.
2. Working with arrays and matrices.
3. Mathmatical operations
4. Data Science and Machine learning

# ***Why use NumPy?***

1. faster than data list.
2. less memomry usage.
3. supoorts multi dimension arrays.
4. provide mathmatical and statistical functions.

1. Installing Numpy

In [ ]:
pip install numpy

import NumPy


In [ ]:
import numpy as np


2. Creating NumPy Arrays

# ***Arrays***

An array is a data structure used to store multiple values of the same data type in a single variable.

From a list

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# ***Two-Dimensional Array(2D)***

A 2D array is an array that stores data in rows and columns, just like an excel sheet or matrix
*italicized text*

In [ ]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


# ***Three-Dimensional Array(3D)***

A 3D array is an array that has three dimensions:

1. Depth(Layers)
2. Rows
3. Columns

In [ ]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ***Array Attributes***

NumPy array attributes provide important information about an array, such as its dimensions, size, shape, and data type.


In [ ]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

print("Shape: ", arr.shape)
print("Dimensions: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimensions:  2
Size:  6
Data Type:  int64


# ***Special Arrays***


# ***zeros Array np.zeros().***

Creates an array where every element is 0.

In [ ]:
import numpy as np

arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# ***Ones Array np.ones()***

Creates an array filled with 1.

In [ ]:
import numpy as np

arr = np.ones((2,4))

print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# ***np.empty()***

Creates an array without initializing values


In [ ]:
import numpy as np
arr = np.empty((2,3))

print(arr)


[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


# ***np.full()***

Creates an array filled with a specified value

In [ ]:
import numpy as np
arr = np.full((3,3), 10)

print(arr)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


# ***np.eye()-- Identity matrix***

In [ ]:
import numpy as np
arr = np.eye((3))

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# ***np.arange()***

Creates equally spaced values.

In [ ]:
import numpy as np

arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# ***np.linspace()***

Creates equally spaced numbers between two values.

In [ ]:
import numpy as np

arr = np.linspace(1, 10, 5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


# ***np.random.rand()***

Random decimal numbers between 0 and 1

In [ ]:
import numpy as np

arr = np.random.rand(3,3)

print(arr)

[[0.01044957 0.22311655 0.31094499]
 [0.36511356 0.82503768 0.5332562 ]
 [0.36090513 0.23078912 0.5393295 ]]


# ***np.random.randint()***

Random integers

In [ ]:
import numpy as np

arr = np.random.randint(1,100,(3,4))

print(arr)

[[49 84 38 48]
 [33 54 63 35]
 [89 85 79 71]]


# ***np.diag()***

Creates a diagonal matrix or extracts diagonal elements.

In [ ]:
import numpy as np

arr = np.diag([5,10,15])

print(arr)

[[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]


# ***Special Arrays in NumPy - 10 Practice questions***

# ***Question 1. Create a 3x4 Numpy array filled with zeros.***

In [ ]:
import numpy as np

arr = np.zeros((3,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ***Question 2. Create a 4x5 Numpy array filled with ones.***

In [ ]:
import numpy as np

arr = np.ones((4,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# ***Question 3. Create a 3x3 array using np.empty() and observe the values.  Explain why values are not initialized.***

In [ ]:
import numpy as np

arr = np.empty((3, 3))

print(arr)



[[2.5e-323 0.0e+000 0.0e+000]
 [0.0e+000 4.9e-323 0.0e+000]
 [0.0e+000 0.0e+000 7.4e-323]]


# ***Question 4. Create a 5x5 Identity matrix using Numpy.***

In [ ]:
import numpy as np

arr= np.eye((5))

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# ***Question 5. Create a 4x4 diagonal matrix with diagonal elements 10, 20, 30, and 40.***

In [ ]:
import numpy as np

arr = np.diag([10, 20, 30, 40])

print(arr)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


# ***Question 6. Create a 5x5 where every element is 99.***

In [ ]:
import numpy as np

arr = np.full((5,5), 99)

print(arr)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


# ***Question 7. Generate 20 equally spaced numbers between 1 and 100.***

In [ ]:
import numpy as np

arr = np.linspace(10, 101, 10)

print(arr)

[ 10.          20.11111111  30.22222222  40.33333333  50.44444444
  60.55555556  70.66666667  80.77777778  90.88888889 101.        ]


# ***Question 8. Create an array conataining numbers from 10 to 100 with a step size of 10.***

In [ ]:
import numpy as np

arr = np.arange(10, 101, 10)

print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


# ***Array Attributes***

Array attributes are the property of a numpy array that provide information about its structure, size, data type, memory usage, and dimensions.

# ***1. ndim (Number of Dimensions)***

ndim tells us how many dimensions (axes) an array has.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.ndim)

1


In [ ]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.ndim)

2


In [ ]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ]
])

print(arr.ndim)

3


# ***2. Shape***

shape tells us how many rows and columns are present.

In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.shape)

(2, 3)


In [ ]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]

])
print(arr.shape)

(3, 2)


In [ ]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr.shape)

(2, 2, 2)


# ***3. Size***

size means total no. of elements formula = Rows*Columns

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.size)

6


# ***4. dtype***

dtype means data type of every element

In [ ]:
import numpy as np
arr = np.array([10, 20, 30])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr = np.array([10.5, 20.2, 30.7])
print(arr.dtype)

float64


In [ ]:
import numpy as np
arr = np.array(["A", "B", "C"])

print(arr.dtype)

<U1


In [ ]:
arr = np.array([True, False, True])
print(arr.dtype)

bool


# ***5. Itemsize***

itemsize tells memory occupied by one element.

In [ ]:
arr = np.array([10, 20, 30])

print(arr.itemsize)

8


In [ ]:
arr = np.array([10.5, 20.4])

print(arr.itemsize)

8


# ***6. Transpose***

transpose means rows becomes columns and columns becomes rows.

In [42]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.T)

[[10 40]
 [20 50]
 [30 60]]


# ***7. nbytes***

nbytes tells total memory occupied by the array formula = item size*size

In [43]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.nbytes)

48
